steps:
  - name: "Deploy Cloud Function: crawler-fetch"
    args:
      - functions
      - deploy
      - --trigger-topic=crawler-fetch # Pub/Sub trigger with topic
      - --runtime=python37
      - --entry-point=crawl_records # Defined function in main.py
      - crawl-fetch # Cloud Function name
  - name: "Deploy Cloud Function: results"
    args:
      - functions
      - deploy
      - --trigger-http # HTTP trigger
      - --runtime=python37
      - --entry-point=results # Defined function in main.py
      - results # Cloud Function name
